"""Added book recommendation model

Revision ID: 0317f59446e0
Revises: 10e54a3f676b
Create Date: 2024-04-15 12:28:23.500514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0317f59446e0'
down_revision: Union[str, None] = '10e54a3f676b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommended_books',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('book_id', sa.BIGINT(), nullable=True),
                    sa.Column('recommended_books', sa.ARRAY(sa.VARCHAR()),
                              server_default=sa.text('ARRAY[]::VARCHAR[]'), nullable=False),
                    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk__recommended_books__book_id__recommended_books')),
                    sa.PrimaryKeyConstraint('id', name='recommended_books_pkey')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommended_books')
    # ### end Alembic commands ###
