"""second migration

Revision ID: 972433b13226
Revises: eca9e766c9ee
Create Date: 2023-11-19 19:38:07.541160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# from src.db.base_class import Base
# from src.db.session import engine

# revision identifiers, used by Alembic.
revision: str = '972433b13226'
down_revision: Union[str, None] = 'eca9e766c9ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
