"""added faq questions

Revision ID: f352d90aaeff
Revises: d098db2e0c59
Create Date: 2024-04-09 20:42:55.844280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import MetaData, Table
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f352d90aaeff'
down_revision: Union[str, None] = 'd098db2e0c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frequently_asked_question',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='frequently_asked_question_pkey')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frequently_asked_question')
    # ### end Alembic commands ###
